module.exports.query = `DROP FUNCTION IF EXISTS capitalize;CREATE FUNCTION capitalize(s VARCHAR(100))
RETURNS VARCHAR(100) DETERMINISTIC
BEGIN
  RETURN CONCAT(UPPER(SUBSTRING(s,1,1)),LOWER(SUBSTRING(s,2)));
END;`
